// import Background from "./clientComponent/background";
import "./globals.css";

import dynamic from "next/dynamic";

const Background = dynamic(() => import("./clientComponent/background"));

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Background />
        {children}
      </body>
    </html>
  );
}
